name: GitHub Metrics

on:
  workflow_dispatch:

  push:
    branches:
      - main

  schedule:
    - cron: "17 3 * * *"

permissions:
  contents: write

jobs:
  generate-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate isometric calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          extras_css: |
            :root {
              background-color: transparent;
              border-radius: 12px;
            }

            .items-wrapper {
              background-color: transparent;
            }

            svg {
              color: #FFFF;
            }
            
            h2.field {
              display: none;
              }
  
            h2, h3 {
              color: #FFFF !important;
              font-size: 12px !important;
            }

            h3 svg, h2 svg {
              fill: #FFFF !important;
              width: 14px !important;
              height: 14px !important;
            }

            div.field {
              font-size: 8px !important;
              color: #9CA3AF;
            }

            div.field > svg {
              width: 10px !important;
              height: 10px !important;
              fill: #9CA3AF
            }

            svg[viewBox="0,0 480,270"] {
              margin-top: -110px !important;
              overflow: visible !important;
            }

            svg[viewBox="0,0 480,270"] path[fill="#ebedf0"] {
              fill: #374151 !important;
            }

            svg[viewBox="0,0 480,270"] path[fill="#9be9a8"] {
              fill: #E9D5FF !important;
            }

            svg[viewBox="0,0 480,270"] path[fill="#40c463"] {
              fill: #C084FC !important;
            }

            svg[viewBox="0,0 480,270"] path[fill="#30a14e"] {
              fill: #9333EA !important;
            }

            svg[viewBox="0,0 480,270"] path[fill="#216e39"] {
              fill: #521057 !important;
            }

              
            extras_js: |
              document.querySelectorAll("h2.field").forEach((el) => {
                if (el.textContent.includes("Contributions calendar")) {
                  el.remove();
                }
              });
